#!/bin/bash
inputs(){
#직접 작성
echo "Please input int1, int2(int1 operator int2)"
read -p "###Input int1, int2: " int1 int2
}

exitPrompt(){
read -p "Do you wish to continue? [y]es od [n]o: " ans
if [ $ans == 'n' ]
then
	echo "Exiting the script. Have a nice day!"
	exit 0
else
	echo "Calculate continue."
	echo "==================="
fi
}

while (true)
do
	clear
	printf "Choose from the following operations: \n"
	printf "[a]Addition [b]Subtraction [c]Multiplication [d]Division\n"
	read -p "###Your choice: " choice

	case $choice in
		[aA])
			inputs
			res=$((int1+int2))
			;;
		[bB])
			inputs
			res=$((int1-int2))
			;;

		[cC])
			inputs
			res=$((int1*int2))
			;;

		[dD])
			inputs
			res=$((int1/int2))
			;;
		*)
			res=0
			echo "wrong choice!"
	esac

	echo "Thr result is: "$res
	exitPrompt
done

