#!/bin/sh
read -p "file/diractory name : " name


if [ ! -e $name ]
then
	echo $name 파일은 존재하지 않습니다.

elif [ -d $name ]
then
	echo $name 파일은 디렉토리 파일입니다.

elif [ -L $name ]
then
	echo $name 파일은 심볼릭링크 파일입입니다.

elif [ -c $name ]
then
	echo $name 파일은 문자장치 파일입니다.

elif [ -b $name ]
then
	echo $name 파일은 블록장치 파일입니다.

elif [ -p $name ]
then
	echo $name 파일은 파이프 파일입니다.

elif [ -S $name ]
then
	echo $name 파일은 소켓 파일입니다.

elif [ -f $name ]
then
	echo $name 파일은 보통 파일입니다.

else
	echo Error: 입력이 정상적으로 전달되지 않았습니다.

fi
